service: aws-node-rest-api-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    MONGO_DB: ${file(config/${self:provider.stage}.yml):mongoDb}

plugins:
  - serverless-offline

package:
  patterns:
    - dist/index.js
    - '!app/**'
    - '!config/**'
    - '!node_modules/**'
    - '!*.json'
    - '!README.md'
  excludeDevDependencies: true

useDotenv: true
configValidationMode: error

functions:
  create:
    handler: dist/index.create
    events:
      - http:
          path: creates
          method: post
  get:
    handler: dist/index.getCardNumber
    events:
      - http:
          path: gets/{token}
          method: get
